#!/bin/bash
# git commit repo/explore/sandbox/whatsnearme -m 'Commit at shutdown'
git add .
git commit -m 'Commit at shutdown'
# git commit .vimrc -m 'Commit at shutdown'
git push --repo=https://github.com/timho13/WhatsNearMe.git/
echo "For pi, please enter ..."
su - pi -c "sudo shutdown -r now"
